/**
 * Links out to a real journey planner.
 *
 * The app used to render a leg-by-leg RTA itinerary with named bus lines. That
 * was generated by a hand-written decision tree, no feed, no stop data, no
 * network calls, so the route numbers and interchanges were invented. RTA's
 * open data portal publishes bus route names and stop order but no bus stop
 * coordinates, so an accurate in-app route cannot be built from it either.
 *
 * Rather than assert a route we cannot verify, we hand the journey to a planner
 * that has the real schedules.
 */

export type TravelMode = 'transit' | 'driving';

interface Point {
  latitude: number;
  longitude: number;
}

const coord = (p: Point) => `${p.latitude},${p.longitude}`;

/** Google Maps directions for this journey, in the given mode. */
export function directionsUrl(origin: Point, destination: Point, mode: TravelMode): string {
  const params = new URLSearchParams({
    api: '1',
    origin: coord(origin),
    destination: coord(destination),
    travelmode: mode === 'transit' ? 'transit' : 'driving',
  });
  return `https://www.google.com/maps/dir/?${params.toString()}`;
}

/**
 * Straight-line distance is exact; travel time is not. Everything we show as a
 * duration is an estimate derived from distance, and is labelled as such.
 */
export const ESTIMATE_NOTE =
  'Estimated from straight-line distance, not a live schedule.';

/**
 * The same journey as an embeddable map.
 *
 * Google's official Embed API requires a billed API key, which a static site
 * cannot hold safely. The long-standing `output=embed` form needs no key and
 * renders the real route, so it is used here; `directionsUrl` above remains for
 * anyone who wants full turn-by-turn.
 */
export function directionsEmbedUrl(
  origin: Point,
  destination: Point,
  mode: TravelMode
): string {
  const params = new URLSearchParams({
    saddr: coord(origin),
    daddr: coord(destination),
    // r = public transport, d = driving
    dirflg: mode === 'transit' ? 'r' : 'd',
    output: 'embed',
  });
  return `https://www.google.com/maps?${params.toString()}`;
}
